version: '3.9'
services:
    db:
        container_name: curious-octopus-db
        image: mysql:5.7
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "33062:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: curious_octopus
        volumes:
            - ./db:/var/lib/mysql

    app:
        container_name: curious-octopus-app
        build:
            context: ./.docker/app
            args:
                PHP_XDEBUG_MODE: off
                PHP_XDEBUG_CLIENT_PORT: 9001
                PHP_XDEBUG_CLIENT_HOST: host.docker.internal
                SYMFONY_CLI_VERSION: 4.28.1
        environment:
            API_URL: 'http://localhost:8091/'
        ports:
            - "8091:80"
            - "9001:9001"
        volumes:
            - ./:/var/www/:cached
        depends_on:
            - db

    rabbitmq:
        container_name: curious-octopus-rabbitmq
        build: ./.docker/rabbitmq
        ports:
            - "15671:15672"
